addons:
  apt:
    packages:
      - nodejs
language: python
python:
  - '3.8'
sudo: false
env:
  - MAKE_TARGET=test TOXENV=eslint
  - MAKE_TARGET=test TOXENV=quality
  - MAKE_TARGET=test TOXENV=csslint
  - MAKE_TARGET=translations_validate
  - MAKE_TARGET=test TOXENV=django22
  - MAKE_TARGET=test TOXENV=django30
  - MAKE_TARGET=test TOXENV=django31
  - MAKE_TARGET=test TOXENV=django32
before_install:
  - pip install -U pip
  - export BOTO_CONFIG=/dev/null
cache:
  directories:
    - $HOME/.cache/pip
install:
  - make requirements_travis
script:
  - make $MAKE_TARGET
branches:
  only:
    - master
after_success: coveralls
