addons:
  apt:
    packages:
      - nodejs
language: python
python:
  - 3.5
  - 3.8
sudo: false
env:
  - TOXENV=django22
  - TOXENV=eslint
  - TOXENV=pylint
  - TOXENV=csslint
  - TOXENV=pycodestyle

before_install:
  - "pip install -U pip"
  - export BOTO_CONFIG=/dev/null
cache:
  directories:
    - $HOME/.cache/pip
install:
  - "make requirements_travis"
script:
  - make test
branches:
  only:
    - master
after_success:
  coveralls
